<?php
// RCVXTR configuration — generated by the installer (/install)
// This file is a template; copy to config.php and adjust as needed.

return [
    // Database driver: 'sqlite' or 'mysql'
    'db_driver'   => 'sqlite',

    // SQLite
    'db_path'     => __DIR__ . '/storage/database.sqlite',

    // MySQL (used when db_driver = 'mysql')
    'db_host'     => '127.0.0.1',
    'db_port'     => '3306',
    'db_name'     => 'rcvxtr',
    'db_user'     => 'root',
    'db_pass'     => '',

    // Application
    'base_url'    => '',
    'debug'       => true,
];
